export const BASE_URL = 'https://petbookers.com.pk/';
// export const BASE_URL = 'http://192.168.1.5:8000/';
// export const BASE_URL= 'https://192.bilalellahi.com/'
export const SELLER_API = 'api/v3/seller/';
export const BUYER_API = 'api/v1/';
// export const CUSTOMER_API = 'api/v3/customer/';

// Country code options for phone field
export const COUNTRY_CODES = [
  {code: '+92', label: '🇵🇰 +92'},
  {code: '+1', label: '🇺🇸 +1'},
  {code: '+7', label: '🇷🇺 +7'},
  {code: '+86', label: '🇨🇳 +86'},
  {code: '+91', label: '🇮🇳 +91'},
  {code: '+81', label: '🇯🇵 +81'},
  {code: '+44', label: '🇬🇧 +44'},
  {code: '+49', label: '🇩🇪 +49'},
  {code: '+33', label: '🇫🇷 +33'},
  {code: '+39', label: '🇮🇹 +39'},
  {code: '+34', label: '🇪🇸 +34'},
  {code: '+31', label: '🇳🇱 +31'},
  {code: '+32', label: '🇧🇪 +32'},
  {code: '+41', label: '🇨🇭 +41'},
  {code: '+43', label: '🇦🇹 +43'},
  {code: '+45', label: '🇩🇰 +45'},
  {code: '+46', label: '🇸🇪 +46'},
  {code: '+47', label: '🇳🇴 +47'},
  {code: '+358', label: '🇫🇮 +358'},
  {code: '+48', label: '🇵🇱 +48'},
  {code: '+420', label: '🇨🇿 +420'},
  {code: '+421', label: '🇸🇰 +421'},
  {code: '+36', label: '🇭🇺 +36'},
  {code: '+40', label: '🇷🇴 +40'},
  {code: '+359', label: '🇧🇬 +359'},
  {code: '+385', label: '🇭🇷 +385'},
  {code: '+386', label: '🇸🇮 +386'},
  {code: '+372', label: '🇪🇪 +372'},
  {code: '+371', label: '🇱🇻 +371'},
  {code: '+370', label: '🇱🇹 +370'},
  {code: '+352', label: '🇱🇺 +352'},
  {code: '+353', label: '🇮🇪 +353'},
  {code: '+351', label: '🇵🇹 +351'},
  {code: '+30', label: '🇬🇷 +30'},
  {code: '+357', label: '🇨🇾 +357'},
  {code: '+356', label: '🇲🇹 +356'},
  {code: '+39', label: '🇻🇦 +39'},
  {code: '+378', label: '🇸🇲 +378'},
  {code: '+377', label: '🇲🇨 +377'},
  {code: '+376', label: '🇦🇩 +376'},
  {code: '+375', label: '🇧🇾 +375'},
  {code: '+380', label: '🇺🇦 +380'},
  {code: '+373', label: '🇲🇩 +373'},
  {code: '+374', label: '🇦🇲 +374'},
  {code: '+995', label: '🇬🇪 +995'},
  {code: '+994', label: '🇦🇿 +994'},

  {code: '+998', label: '🇺🇿 +998'},
  {code: '+996', label: '🇰🇬 +996'},
  {code: '+992', label: '🇹🇯 +992'},
  {code: '+993', label: '🇹🇲 +993'},
  {code: '+90', label: '🇹🇷 +90'},
  {code: '+98', label: '🇮🇷 +98'},
  {code: '+964', label: '🇮🇶 +964'},
  {code: '+963', label: '🇸🇾 +963'},
  {code: '+961', label: '🇱🇧 +961'},
  {code: '+972', label: '🇮🇱 +972'},
  {code: '+970', label: '🇵🇸 +970'},
  {code: '+962', label: '🇯🇴 +962'},
  {code: '+966', label: '🇸🇦 +966'},
  {code: '+965', label: '🇰🇼 +965'},
  {code: '+973', label: '🇧🇭 +973'},
  {code: '+974', label: '🇶🇦 +974'},
  {code: '+971', label: '🇦🇪 +971'},
  {code: '+968', label: '🇴🇲 +968'},
  {code: '+967', label: '🇾🇪 +967'},
  {code: '+20', label: '🇪🇬 +20'},
  {code: '+218', label: '🇱🇾 +218'},
  {code: '+216', label: '🇹🇳 +216'},
  {code: '+213', label: '🇩🇿 +213'},
  {code: '+212', label: '🇲🇦 +212'},
  {code: '+222', label: '🇲🇷 +222'},
  {code: '+221', label: '🇸🇳 +221'},
  {code: '+220', label: '🇬🇲 +220'},
  {code: '+223', label: '🇲🇱 +223'},
  {code: '+224', label: '🇬🇳 +224'},
  {code: '+225', label: '🇨🇮 +225'},
  {code: '+226', label: '🇧🇫 +226'},
  {code: '+227', label: '🇳🇪 +227'},
  {code: '+228', label: '🇹🇬 +228'},
  {code: '+229', label: '🇧🇯 +229'},
  {code: '+230', label: '🇲🇺 +230'},
  {code: '+231', label: '🇱🇷 +231'},
  {code: '+232', label: '🇸🇱 +232'},
  {code: '+233', label: '🇬🇭 +233'},
  {code: '+234', label: '🇳🇬 +234'},
  {code: '+235', label: '🇹🇩 +235'},
  {code: '+236', label: '🇨🇫 +236'},
  {code: '+237', label: '🇨🇲 +237'},
  {code: '+238', label: '🇨🇻 +238'},
  {code: '+239', label: '🇸🇹 +239'},
  {code: '+240', label: '🇬🇶 +240'},
  {code: '+241', label: '🇬🇦 +241'},
  {code: '+242', label: '🇨🇬 +242'},
  {code: '+243', label: '🇨🇩 +243'},
  {code: '+244', label: '🇦🇴 +244'},
  {code: '+245', label: '🇬🇼 +245'},
  {code: '+246', label: '🇮🇴 +246'},
  {code: '+248', label: '🇸🇨 +248'},
  {code: '+249', label: '🇸🇩 +249'},
  {code: '+250', label: '🇷🇼 +250'},
  {code: '+251', label: '🇪🇹 +251'},
  {code: '+252', label: '🇸🇴 +252'},
  {code: '+253', label: '🇩🇯 +253'},
  {code: '+254', label: '🇰🇪 +254'},
  {code: '+255', label: '🇹🇿 +255'},
  {code: '+256', label: '🇺🇬 +256'},
  {code: '+257', label: '🇧🇮 +257'},
  {code: '+258', label: '🇲🇿 +258'},
  {code: '+260', label: '🇿🇲 +260'},
  {code: '+261', label: '🇲🇬 +261'},
  {code: '+262', label: '🇷🇪 +262'},
  {code: '+263', label: '🇿🇼 +263'},
  {code: '+264', label: '🇳🇦 +264'},
  {code: '+265', label: '🇲🇼 +265'},
  {code: '+266', label: '🇱🇸 +266'},
  {code: '+267', label: '🇧🇼 +267'},
  {code: '+268', label: '🇸🇿 +268'},
  {code: '+269', label: '🇰🇲 +269'},
  {code: '+290', label: '🇸🇭 +290'},
  {code: '+291', label: '🇪🇷 +291'},
  {code: '+297', label: '🇦🇼 +297'},
  {code: '+298', label: '🇫🇴 +298'},
  {code: '+299', label: '🇬🇱 +299'},
  {code: '+500', label: '🇫🇰 +500'},
  {code: '+501', label: '🇧🇿 +501'},
  {code: '+502', label: '🇬🇹 +502'},
  {code: '+503', label: '🇸🇻 +503'},
  {code: '+504', label: '🇭🇳 +504'},
  {code: '+505', label: '🇳🇮 +505'},
  {code: '+506', label: '🇨🇷 +506'},
  {code: '+507', label: '🇵🇦 +507'},
  {code: '+508', label: '🇵🇲 +508'},
  {code: '+509', label: '🇭🇹 +509'},
  {code: '+590', label: '🇬🇵 +590'},
  {code: '+591', label: '🇧🇴 +591'},
  {code: '+592', label: '🇬🇾 +592'},
  {code: '+593', label: '🇪🇨 +593'},
  {code: '+594', label: '🇬🇫 +594'},
  {code: '+595', label: '🇵🇾 +595'},
  {code: '+596', label: '🇲🇶 +596'},
  {code: '+597', label: '🇸🇷 +597'},
  {code: '+598', label: '🇺🇾 +598'},
  {code: '+599', label: '🇧🇶 +599'},
  {code: '+670', label: '🇹🇱 +670'},
  {code: '+672', label: '🇦🇶 +672'},
  {code: '+673', label: '🇧🇳 +673'},
  {code: '+674', label: '🇳🇷 +674'},
  {code: '+675', label: '🇵🇬 +675'},
  {code: '+676', label: '🇹🇴 +676'},
  {code: '+677', label: '🇸🇧 +677'},
  {code: '+678', label: '🇻🇺 +678'},
  {code: '+679', label: '🇫🇯 +679'},
  {code: '+680', label: '🇵🇼 +680'},
  {code: '+681', label: '🇼🇫 +681'},
  {code: '+682', label: '🇨🇰 +682'},
  {code: '+683', label: '🇳🇺 +683'},
  {code: '+684', label: '🇦🇸 +684'},
  {code: '+685', label: '🇼🇸 +685'},
  {code: '+686', label: '🇰🇮 +686'},
  {code: '+687', label: '🇳🇨 +687'},
  {code: '+688', label: '🇹🇻 +688'},
  {code: '+689', label: '🇵🇫 +689'},
  {code: '+690', label: '🇹🇰 +690'},
  {code: '+691', label: '🇫🇲 +691'},
  {code: '+692', label: '🇲🇭 +692'},
  {code: '+850', label: '🇰🇵 +850'},
  {code: '+852', label: '🇭🇰 +852'},
  {code: '+853', label: '🇲🇴 +853'},
  {code: '+855', label: '🇰🇭 +855'},
  {code: '+856', label: '🇱🇦 +856'},
  {code: '+880', label: '🇧🇩 +880'},
  {code: '+886', label: '🇹🇼 +886'},
  {code: '+960', label: '🇲🇻 +960'},
  {code: '+961', label: '🇱🇧 +961'},
  {code: '+962', label: '🇯🇴 +962'},
  {code: '+963', label: '🇸🇾 +963'},
  {code: '+964', label: '🇮🇶 +964'},
  {code: '+965', label: '🇰🇼 +965'},
  {code: '+966', label: '🇸🇦 +966'},
  {code: '+967', label: '🇾🇪 +967'},
  {code: '+968', label: '🇴🇲 +968'},
  {code: '+970', label: '🇵🇸 +970'},
  {code: '+971', label: '🇦🇪 +971'},
  {code: '+972', label: '🇮🇱 +972'},
  {code: '+973', label: '🇧🇭 +973'},
  {code: '+974', label: '🇶🇦 +974'},
  {code: '+975', label: '🇧🇹 +975'},
  {code: '+976', label: '🇲🇳 +976'},
  {code: '+977', label: '🇳🇵 +977'},
  {code: '+992', label: '🇹🇯 +992'},
  {code: '+993', label: '🇹🇲 +993'},
  {code: '+994', label: '🇦🇿 +994'},
  {code: '+995', label: '🇬🇪 +995'},
  {code: '+996', label: '🇰🇬 +996'},
  {code: '+998', label: '🇺🇿 +998'},
];

// Pakistan States and Cities
export const stateKeys = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa',
  'Balochistan',
  'Gilgit-Baltistan',
  'Azad Kashmir',
  'Islamabad',
];

// Comprehensive list of Pakistan cities by state
export const citiesByState = {
  Punjab: [
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Gujranwala',
    'Sialkot',
    'Sargodha',
    'Bahawalpur',
    'Sheikhupura',
    'Jhang',
    'Rahim Yar Khan',
    'Gujrat',
    'Kasur',
    'Mardan',
    'Sahiwal',
    'Okara',
    'Wah Cantonment',
    'Dera Ghazi Khan',
    'Mirpur Khas',
    'Nawabshah',
    'Chiniot',
    'Kotri',
    'Kāmoke',
    'Hafizabad',
    'Kohat',
    'Jacobabad',
    'Shikarpur',
    'Muzaffargarh',
    'Khanpur',
    'Gojra',
    'Bahawalnagar',
    'Muridke',
    'Pakpattan',
    'Abottabad',
    'Tando Adam',
    'Jhelum',
    'Kahuta',
    'Gujar Khan',
    'Kot Addu',
    'Hasan Abdal',
    'Kamalia',
    'Umerkot',
    'Ahmedpur East',
    'Kotri',
    'Larkana',
    'Mandi Bahauddin',
    'Toba Tek Singh',
    'Nowshera',
    'Shahdadpur',
    'Mianwali',
    'Bhakkar',
    'Jaranwala',
    'Chishtian',
    'Daska',
    'Mandi Bahauddin',
    'Kharian',
    'Mian Channu',
    'Burewala',
    'Dera Ismail Khan',
    'Wazirabad',
    'Naushahro Firoz',
    'Chakwal',
    'Khanewal',
    'Hafizabad',
    'Kohat',
    'Jacobabad',
    'Shikarpur',
    'Muzaffargarh',
    'Khanpur',
    'Gojra',
    'Bahawalnagar',
    'Muridke',
    'Pakpattan',
    'Abottabad',
    'Tando Adam',
    'Jhelum',
    'Kahuta',
    'Gujar Khan',
    'Kot Addu',
    'Hasan Abdal',
    'Kamalia',
    'Umerkot',
    'Ahmedpur East',
    'Kotri',
    'Larkana',
    'Mandi Bahauddin',
    'Toba Tek Singh',
    'Nowshera',
    'Shahdadpur',
    'Mianwali',
    'Bhakkar',
    'Jaranwala',
    'Chishtian',
    'Daska',
    'Mandi Bahauddin',
    'Kharian',
    'Mian Channu',
    'Burewala',
    'Dera Ismail Khan',
    'Wazirabad',
    'Naushahro Firoz',
    'Chakwal',
    'Khanewal',
  ],
  Sindh: [
    'Karachi',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah',
    'Mirpur Khas',
    'Jacobabad',
    'Shikarpur',
    'Khairpur',
    'Dadu',
    'Tando Allahyar',
    'Tando Adam',
    'Kotri',
    'Shahdadpur',
    'Matiari',
    'Ghotki',
    'Naushahro Firoz',
    'Sanghar',
    'Mirpur Khas',
    'Umerkot',
    'Tharparkar',
    'Badin',
    'Tando Muhammad Khan',
    'Jamshoro',
    'Thatta',
    'Sujawal',
    'Kashmore',
    'Shikarpur',
    'Jacobabad',
    'Kamber Shahdadkot',
    'Larkana',
    'Qamber Shahdadkot',
    'Kashmore',
    'Shikarpur',
    'Jacobabad',
    'Kamber Shahdadkot',
    'Larkana',
    'Qamber Shahdadkot',
  ],
  'Khyber Pakhtunkhwa': [
    'Peshawar',
    'Mardan',
    'Mingora',
    'Kohat',
    'Abbottabad',
    'Dera Ismail Khan',
    'Nowshera',
    'Charsadda',
    'Swabi',
    'Mansehra',
    'Bannu',
    'Hangu',
    'Haripur',
    'Karak',
    'Lakki Marwat',
    'Tank',
    'Dir',
    'Buner',
    'Swat',
    'Shangla',
    'Kohistan',
    'Upper Dir',
    'Lower Dir',
    'Malakand',
    'Chitral',
    'Bajaur',
    'Mohmand',
    'Khyber',
    'Orakzai',
    'Kurram',
    'North Waziristan',
    'South Waziristan',
    'Tribal Areas',
  ],
  Balochistan: [
    'Quetta',
    'Turbat',
    'Khuzdar',
    'Chaman',
    'Gwadar',
    'Dera Murad Jamali',
    'Dera Allah Yar',
    'Usta Muhammad',
    'Loralai',
    'Pishin',
    'Turbat',
    'Khuzdar',
    'Chaman',
    'Gwadar',
    'Dera Murad Jamali',
    'Dera Allah Yar',
    'Usta Muhammad',
    'Loralai',
    'Pishin',
    'Qila Abdullah',
    'Kech',
    'Panjgur',
    'Washuk',
    'Awaran',
    'Barkhan',
    'Bolan',
    'Chagai',
    'Dera Bugti',
    'Harnai',
    'Jafarabad',
    'Jhal Magsi',
    'Kacchi',
    'Kalat',
    'Kech',
    'Kharan',
    'Kohlu',
    'Lasbela',
    'Mastung',
    'Musakhel',
    'Naseerabad',
    'Nushki',
    'Qila Abdullah',
    'Qila Saifullah',
    'Quetta',
    'Sherani',
    'Sibi',
    'Sohbatpur',
    'Washuk',
    'Zhob',
    'Ziarat',
  ],
  'Gilgit-Baltistan': [
    'Gilgit',
    'Skardu',
    'Hunza',
    'Nagar',
    'Ghanche',
    'Shigar',
    'Kharmang',
    'Gultari',
    'Roundu',
    'Astore',
    'Diamer',
    'Ghizer',
    'Baltistan',
    'Karakoram',
    'Hunza Valley',
    'Nagar Valley',
    'Shigar Valley',
    'Kharmang Valley',
    'Gultari Valley',
    'Roundu Valley',
    'Astore Valley',
    'Diamer Valley',
    'Ghizer Valley',
    'Baltistan Valley',
    'Karakoram Valley',
  ],
  'Azad Kashmir': [
    'Muzaffarabad',
    'Mirpur',
    'Bhimber',
    'Kotli',
    'Poonch',
    'Bagh',
    'Haveli',
    'Sudhnuti',
    'Neelum',
    'Jhelum Valley',
    'Leepa Valley',
    'Rawalakot',
    'Pallandri',
    'Kahuta',
    'Hajira',
    'Charhoi',
    'Chakswari',
    'Dadyal',
    'Kotli',
    'Nakyal',
    'Sehnsa',
    'Tatta Pani',
    'Trar Dewan',
    'Trarkhel',
    'Tolipir',
    'Toli Pir',
    'Toli Pir',
  ],
  Islamabad: [
    'Islamabad',
    'Rawalpindi',
    'Murree',
    'Kahuta',
    'Gujar Khan',
    'Kotli Sattian',
    'Taxila',
    'Wah Cantonment',
    'Attock',
    'Fateh Jang',
    'Hasan Abdal',
    'Jand',
    'Kamra',
    'Pindigheb',
    'Sangjani',
    'Shahpur',
    'Talagang',
    'Tarnol',
    'Ziarat',
  ],
};
